OpenNSL API Guide and Reference Manual: include/examples/util.h File Reference
include/examples/util.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sal/driver.h>
Defines
#define OPENNSL_BOOT_F_DEFAULT 0x000000
#define OPENNSL_BOOT_F_WARM_BOOT 0x200000
Functions
int example_read_user_choice (int *choice)
Read numeric menu choice from user.
int example_switch_default_vlan_config (int unit)
Add all ports to default vlan.
void l2_print_mac (char *str, opennsl_mac_t mac_address)
To print the MAC address.
unsigned int opennsl_boot_flags_get (void)
To get boot flags fetched from environment.
int opennsl_ip_parse (char *ip_str, unsigned int *ip_val)
Parse IP string into a IP value.
int opennsl_mac_parse (char *buf, unsigned char *macp)
Parse MAC address string.
void print_ip_addr (char *str, unsigned int host)
To print IP address in dotted decimal format.
Define Documentation
#define OPENNSL_BOOT_F_DEFAULT 0x000000
Definition at line 33 of file util.h.
Referenced by opennsl_boot_flags_get().
#define OPENNSL_BOOT_F_WARM_BOOT 0x200000
Definition at line 34 of file util.h.
Referenced by main().
Function Documentation
int example_read_user_choice (int * choice)
Read numeric menu choice from user.
Parameters:
choice [IN/OUT] choice
Returns:
OPENNSL_E_xxx OpenNSL API return code
Definition at line 77 of file util.c.
References FALSE, MAX_DIGITS_IN_CHOICE, OPENNSL_E_FAIL, OPENNSL_E_NONE, and TRUE.
Referenced by example_knet_intf_create(), and main().
int example_switch_default_vlan_config (int unit)
Add all ports to default vlan.
Parameters:
unit [IN] unit number
Returns:
OPENNSL_E_XXX OpenNSL API return code
Definition at line 45 of file util.c.
References DEFAULT_VLAN, opennsl_port_config_s::e, OPENNSL_E_NONE, opennsl_errmsg, opennsl_port_config_get(), and opennsl_vlan_port_add().
Referenced by main().
void l2_print_mac (char * str, opennsl_mac_t mac_address)
To print the MAC address.
Returns:
void
Definition at line 183 of file util.c.
Referenced by example_create_l3_intf().
unsigned int opennsl_boot_flags_get (void)
To get boot flags fetched from environment.
Returns:
unsigned int Boot flags
Definition at line 318 of file util.c.
References NULL, OPENNSL_BOOT_F_DEFAULT, and opennsl_ctoi().
Referenced by main().
int opennsl_ip_parse (char * ip_str, unsigned int * ip_val)
Parse IP string into a IP value.
Parameters:
ip_str [IN] IP address in decimal dotted format
ip_val [OUT] IP address in integer format
Returns:
OPENNSL_E_XXX OpenNSL API return code
Definition at line 207 of file util.c.
References NULL.
int opennsl_mac_parse (char * buf, unsigned char * macp)
Parse MAC address string.
Parameters:
buf [IN] MAC address in string format
macp [OUT] MAC address in integer format
Returns:
OPENNSL_E_XXX OpenNSL API return code
Definition at line 118 of file util.c.
References MAC_ADDR_LEN, NULL, OPENNSL_E_FAIL, and OPENNSL_E_NONE.
void print_ip_addr (char * str, unsigned int host)
To print IP address in dotted decimal format.
Parameters:
str [OUT] Buffer to store the IP address
host [IN] MAC address in integer format
Returns:
void
Definition at line 250 of file util.c.
Referenced by example_add_host(), and example_set_default_route().