OpenNSL API Guide and Reference Manual: Class of Service Queue Configuration
Class of Service Queue Configuration
Data Structures
struct opennsl_cosq_bst_profile_s
Files
file cosq.h
Typedefs
typedef enum opennsl_bst_stat_id_e opennsl_bst_stat_id_t
BST Tracing statistics resources type eumerations.
typedef struct
opennsl_cosq_bst_profile_s opennsl_cosq_bst_profile_t
Enumerations
enum opennsl_bst_stat_id_e {
opennslBstStatIdDevice = 0,
opennslBstStatIdEgrPool = 1,
opennslBstStatIdEgrMCastPool = 2,
opennslBstStatIdIngPool = 3,
opennslBstStatIdPortPool = 4,
opennslBstStatIdPriGroupShared = 5,
opennslBstStatIdPriGroupHeadroom = 6,
opennslBstStatIdUcast = 7,
opennslBstStatIdMcast = 8,
opennslBstStatIdHeadroomPool = 9,
opennslBstStatIdEgrUCastPortShared = 10,
opennslBstStatIdEgrPortShared = 11,
opennslBstStatIdRQEQueue = 12,
opennslBstStatIdRQEPool = 13,
opennslBstStatIdUcastGroup = 14,
opennslBstStatIdCpuQueue = 15,
opennslBstStatIdMaxCount = 16
}
BST Tracing statistics resources type eumerations.
Functions
int opennsl_cosq_bst_profile_get (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid, opennsl_cosq_bst_profile_t *profile) LIB_DLL_EXPORTED
Set/Get the BST profile for CosQ objects.
int opennsl_cosq_bst_profile_set (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid, opennsl_cosq_bst_profile_t *profile) LIB_DLL_EXPORTED
Set/Get the BST profile for CosQ objects.
int opennsl_cosq_bst_stat_clear (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid) LIB_DLL_EXPORTED
Clear the current statistic/count of specified BST profile.
int opennsl_cosq_bst_stat_get (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid, uint32 options, uint64 *value) LIB_DLL_EXPORTED
Get the current statistic/count of specified BST profile.
int opennsl_cosq_bst_stat_multi_get (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, uint32 options, int max_values, opennsl_bst_stat_id_t *id_list, uint64 *values) LIB_DLL_EXPORTED
Get the current statistic/count of multiple specified BST profile.
int opennsl_cosq_bst_stat_sync (int unit, opennsl_bst_stat_id_t bid) LIB_DLL_EXPORTED
Sync the HW stats value to SW copy for all or given BST resource.
int opennsl_cosq_mapping_get (int unit, opennsl_cos_t priority, opennsl_cos_queue_t *cosq) LIB_DLL_EXPORTED
Get or set the mapping from internal priority to CoS queue.
int opennsl_cosq_mapping_set (int unit, opennsl_cos_t priority, opennsl_cos_queue_t cosq) LIB_DLL_EXPORTED
Get or set the mapping from internal priority to CoS queue.
Typedef Documentation
typedef enum opennsl_bst_stat_id_e opennsl_bst_stat_id_t
BST Tracing statistics resources type eumerations.
typedef struct opennsl_cosq_bst_profile_s opennsl_cosq_bst_profile_t
Enumeration Type Documentation
enum opennsl_bst_stat_id_e
BST Tracing statistics resources type eumerations.
Enumerator:
opennslBstStatIdDevice
Per device BST tracing resource.
opennslBstStatIdEgrPool
Per Egress Pool BST tracing resource.
opennslBstStatIdEgrMCastPool
Per Egress Pool BST tracing resource(Multicast)
opennslBstStatIdIngPool
Per Ingress Pool BST tracing resource.
opennslBstStatIdPortPool
Per Port Pool BST tracing resource.
opennslBstStatIdPriGroupShared
Per Shared Priority Group Pool BST tracing resource.
opennslBstStatIdPriGroupHeadroom
Per Priority Group Headroom BST tracing resource.
opennslBstStatIdUcast
BST Tracing resource for unicast.
opennslBstStatIdMcast
BST Tracing resource for multicast.
opennslBstStatIdHeadroomPool
BST Tracing the Headroom Pool Usage Count.
opennslBstStatIdEgrUCastPortShared
BST Tracing resource UC per egress port SP.
opennslBstStatIdEgrPortShared
BST Tracing resource per egress port SP.
opennslBstStatIdRQEQueue
BST Tracing resource per RQE queue.
opennslBstStatIdRQEPool
BST tracing resource per RQE Pool.
opennslBstStatIdUcastGroup
BST Tracing resource per Ucast queue group.
opennslBstStatIdCpuQueue
BST Tracking resource per CPU queue.
opennslBstStatIdMaxCount
Must be the last.
Not a usable value.
Definition at line 108 of file cosq.h.
Function Documentation
int opennsl_cosq_bst_profile_get (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid, opennsl_cosq_bst_profile_t * profile)
Set/Get the BST profile for CosQ objects.
Description
Configure or retrieve the BST (buffer statistics tracking) configuration for the specified MMU resource. MMU resource is identified by the combination of port, cosq and bid parameters. port parameter can be port gport, queue gport. bid parameter identifies the MMU resource, for instance the bid opennslBstStatIdEgrPool identifies the egress service pool resource. cosq parameter identifies the object withing the various instances of resources within the identified resource. Note: For bid=opennslBstStatIdHeadroomPool, returns OPENNSL_E_PARAM as there is no BST configuration required for Headroom Pool The bid parameter can be one of the following from the table.
Parameters:
unit [IN] Unit number.
gport [IN]
cosq [IN] Cosq object offset identifier
bid [IN] BST stat ID to identify the COSQ resource/object
profile [OUT] BST profile configuration
Return values:
OPENNSL_E_NONE
OPENNSL_E_XXX
int opennsl_cosq_bst_profile_set (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid, opennsl_cosq_bst_profile_t * profile)
Set/Get the BST profile for CosQ objects.
Description
Configure or retrieve the BST (buffer statistics tracking) configuration for the specified MMU resource. MMU resource is identified by the combination of port, cosq and bid parameters. port parameter can be port gport, queue gport. bid parameter identifies the MMU resource, for instance the bid opennslBstStatIdEgrPool identifies the egress service pool resource. cosq parameter identifies the object withing the various instances of resources within the identified resource. Note: For bid=opennslBstStatIdHeadroomPool, returns OPENNSL_E_PARAM as there is no BST configuration required for Headroom Pool The bid parameter can be one of the following from the table.
Parameters:
unit [IN] Unit number.
gport [IN]
cosq [IN] Cosq object offset identifier
bid [IN] BST stat ID to identify the COSQ resource/object
profile [IN] BST profile configuration
Return values:
OPENNSL_E_NONE
OPENNSL_E_XXX
int opennsl_cosq_bst_stat_clear (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid)
Clear the current statistic/count of specified BST profile.
Description
Clear the BST (buffer statistics tracking) statistic for the specified MMU resource. MMU resource is identified by the combination of port, cosq and bid parameters. port parameter can be port gport, queue gport. bid parameter identifies the MMU resource, for instance the bid opennslBstStatIdEgrPool identifies the egress service pool resource. cosq parameter identifies the object withing the various instances of resources within the identified resource. gport value of -1 will clear stats on all ports.
Parameters:
unit [IN] Unit number.
gport [IN] Device or logical port or GPORT ID
cosq [IN] Cosq object offset identifier
bid [IN] BST stat ID to identify the COSQ resource/object
Return values:
OPENNSL_E_NONE
OPENNSL_E_XXX
Referenced by main().
int opennsl_cosq_bst_stat_get (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, opennsl_bst_stat_id_t bid, uint32 options, uint64 * value)
Get the current statistic/count of specified BST profile.
Description
Retrieve the BST (buffer statistics tracking) statistic for the specified MMU resource. MMU resource is identified by the combination of port, cosq and bid parameters. port parameter can be port gport, queue gport. bid parameter identifies the MMU resource, for instance the flag opennslBstStatIdEgrPool identifies the egress service pool resource. cosq parameter identifies the object withing the various instances of resources within the identified resource. if option OPENNSL_COSQ_STAT_CLEAR is present, a memory/register clear will be performed after stat reading. .
Parameters:
unit [IN] Unit number.
gport [IN]
cosq [IN] Cosq object offset identifier
bid [IN] BST stat ID to identify the COSQ resource/object
options [IN] options to perform clear-on-read
value [OUT]
Return values:
OPENNSL_E_NONE
OPENNSL_E_XXX
Referenced by main().
int opennsl_cosq_bst_stat_multi_get (int unit, opennsl_gport_t gport, opennsl_cos_queue_t cosq, uint32 options, int max_values, opennsl_bst_stat_id_t * id_list, uint64 * values)
Get the current statistic/count of multiple specified BST profile.
Description
Retrieve the BST (buffer statistics tracking) statistic for multiple specified MMU resource. MMU resource is identified by the combination of port, cosq and bid parameters. port parameter can be port gport, queue gport. bid parameter identifies the MMU resource, for instance the flag opennslBstStatIdEgrPool identifies the egress service pool resource. cosq parameter identifies the object withing the various instances of resources within the identified resource. if option OPENNSL_COSQ_STAT_CLEAR is present, a memory/register clear will be performed after stat reading. .
Parameters:
unit [IN] Unit number.
gport [IN] Device or logical port or GPORT ID
cosq [IN] Cosq object offset identifier
options [IN] options to perform clear-on-read
max_values [IN] Number of elements in id_list and pvalue
id_list [IN] Array of BST stat ID list to identify the COSQ resource/object
values [OUT]
Return values:
OPENNSL_E_NONE
OPENNSL_E_XXX
int opennsl_cosq_bst_stat_sync (int unit, opennsl_bst_stat_id_t bid)
Sync the HW stats value to SW copy for all or given BST resource.
Description
API to sync the Hardware stats for all or given BST resources to the Software copy. During this sync, BST status will be disabled, in order to maintain consistency of the stats to a defined time and Post sync, the BST status will be restored. This is required to be used before calling bst_stat_get() to get latest or updated stats value.
Parameters:
unit [IN] Unit number.
bid [IN] BST stat ID to identify the COSQ resource/object
Return values:
OPENNSL_E_NONE
OPENNSL_E_XXX
Referenced by main().
int opennsl_cosq_mapping_get (int unit, opennsl_cos_t priority, opennsl_cos_queue_t * cosq)
Get or set the mapping from internal priority to CoS queue.
Description
Configure or retrieve the mapping from the internal priority value to Cos Queue. The internal priority is usually initialized from the packet priority. For tagged packets the priority is extracted from the PRI field of the tag. For untagged packets, the priority is specified using the API =opennsl_port_untagged_priority_set . On some devices, the mapping tables may be shared among several ports, so setting one port's mappings may affect other ports'. On some devices, packets directed to the CPU interface port may have their priority assigned independent of this setting. For more information see =opennsl_switch_control_set . On some devices, a port value of -1 or gport type for system configuration will configure all ports. Some devices support Enhanced Transmission Selection (ETS) which requires to use GPORT ID for the port argument. When the ETS mode is enabled, they configure and retrive the mapping from the internal priority to the offset (which is equal to the value of cosq) of the unicast queues and multicast queues attached to the egress port. Most devices have 8 internal priorities (0 to 7).
Parameters:
unit [IN] Unit number.
priority [IN] internal priority to map
cosq [OUT] Cos queue to which to map the chosen priority
Return values:
OPENNSL_E_NONE
OPENNSL_E_PARAM Invalid priority, or device not configured for the number of CoS queues specified.
OPENNSL_E_XXX
int opennsl_cosq_mapping_set (int unit, opennsl_cos_t priority, opennsl_cos_queue_t cosq)
Get or set the mapping from internal priority to CoS queue.
Description
Configure or retrieve the mapping from the internal priority value to Cos Queue. The internal priority is usually initialized from the packet priority. For tagged packets the priority is extracted from the PRI field of the tag. For untagged packets, the priority is specified using the API =opennsl_port_untagged_priority_set . On some devices, the mapping tables may be shared among several ports, so setting one port's mappings may affect other ports'. On some devices, packets directed to the CPU interface port may have their priority assigned independent of this setting. For more information see =opennsl_switch_control_set . On some devices, a port value of -1 or gport type for system configuration will configure all ports. Some devices support Enhanced Transmission Selection (ETS) which requires to use GPORT ID for the port argument. When the ETS mode is enabled, they configure and retrive the mapping from the internal priority to the offset (which is equal to the value of cosq) of the unicast queues and multicast queues attached to the egress port. Most devices have 8 internal priorities (0 to 7).
Parameters:
unit [IN] Unit number.
priority [IN] internal priority to map
cosq [IN] Cos queue to which to map the chosen priority
Return values:
OPENNSL_E_NONE
OPENNSL_E_PARAM Invalid priority, or device not configured for the number of CoS queues specified.
OPENNSL_E_XXX